// VOTE CONSTANT
export const ADDING_ONE_TO_VOTE = "ADD_ONE_TO_VOTE";
export const ADDED_ONE_TO_VOTE = "MINUS_ONE_TO_VOTE";
export const MINUSING_ONE_TO_VOTE = "MINUS_ONE_TO_VOTE";
export const MINUSED_ONE_TO_VOTE = "MINUS_ONE_TO_VOTE";

// COMMENT CONSTANT
export const ADDING_COMMENT = "ADDING_COMMENT";
export const ADDED_COMMENT = "ADDED_COMMENT";

// ADD POST CONSTANT
export const ADDING_POST = "ADD_POST";
export const ADDED_POST = "ADD_POST";
export const UPDATING_POSTS = "UPDATING_POSTS";
export const UPDATED_POSTS = "UPDATED_POSTS";
export const UPDATING_SUB_POSTS = "UPDATING_SUB_POSTS";
export const UPDATED_SUB_POSTS = "UPDATED_SUB_POSTS";

// USERS CONSTANT
export const USER_LOGGING_IN = "USER_LOGGING_IN";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const REGISTERING_USER = 'REGISTERING_USER'
export const REGISTERED_USER = 'REGISTERED_USER'
